// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dsbasko/back-office.uz/apps/todo/internal/controllers/rest/handlers (interfaces: TaskMutator)

// Package mock_controller_rest_handlers is a generated GoMock package.
package mock_controller_rest_handlers

import (
	context "context"
	reflect "reflect"

	entities "github.com/dsbasko/back-office.uz/apps/todo/internal/entities"
	api "github.com/dsbasko/back-office.uz/apps/todo/pkg/api"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskMutator is a mock of TaskMutator interface.
type MockTaskMutator struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMutatorMockRecorder
}

// MockTaskMutatorMockRecorder is the mock recorder for MockTaskMutator.
type MockTaskMutatorMockRecorder struct {
	mock *MockTaskMutator
}

// NewMockTaskMutator creates a new mock instance.
func NewMockTaskMutator(ctrl *gomock.Controller) *MockTaskMutator {
	mock := &MockTaskMutator{ctrl: ctrl}
	mock.recorder = &MockTaskMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskMutator) EXPECT() *MockTaskMutatorMockRecorder {
	return m.recorder
}

// CheckTask mocks base method.
func (m *MockTaskMutator) CheckTask(arg0 context.Context, arg1 string, arg2 api.CheckTaskRequestV1) (entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTask indicates an expected call of CheckTask.
func (mr *MockTaskMutatorMockRecorder) CheckTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTask", reflect.TypeOf((*MockTaskMutator)(nil).CheckTask), arg0, arg1, arg2)
}

// CreateTask mocks base method.
func (m *MockTaskMutator) CreateTask(arg0 context.Context, arg1 api.CreateTaskRequestV1) (entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskMutatorMockRecorder) CreateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskMutator)(nil).CreateTask), arg0, arg1)
}
