// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dsbasko/back-office.uz/apps/todo/internal/controllers/rest/handlers (interfaces: TaskProvider)

// Package mock_controller_rest_handlers is a generated GoMock package.
package mock_controller_rest_handlers

import (
	context "context"
	reflect "reflect"

	entities "github.com/dsbasko/back-office.uz/apps/todo/internal/entities"
	api "github.com/dsbasko/back-office.uz/apps/todo/pkg/api"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskProvider is a mock of TaskProvider interface.
type MockTaskProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTaskProviderMockRecorder
}

// MockTaskProviderMockRecorder is the mock recorder for MockTaskProvider.
type MockTaskProviderMockRecorder struct {
	mock *MockTaskProvider
}

// NewMockTaskProvider creates a new mock instance.
func NewMockTaskProvider(ctrl *gomock.Controller) *MockTaskProvider {
	mock := &MockTaskProvider{ctrl: ctrl}
	mock.recorder = &MockTaskProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskProvider) EXPECT() *MockTaskProviderMockRecorder {
	return m.recorder
}

// FindTask mocks base method.
func (m *MockTaskProvider) FindTask(arg0 context.Context, arg1 api.FindTaskRequestV1) (entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTask", arg0, arg1)
	ret0, _ := ret[0].(entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTask indicates an expected call of FindTask.
func (mr *MockTaskProviderMockRecorder) FindTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTask", reflect.TypeOf((*MockTaskProvider)(nil).FindTask), arg0, arg1)
}

// FindTasks mocks base method.
func (m *MockTaskProvider) FindTasks(arg0 context.Context, arg1 api.FindTasksRequestV1) ([]entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTasks", arg0, arg1)
	ret0, _ := ret[0].([]entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTasks indicates an expected call of FindTasks.
func (mr *MockTaskProviderMockRecorder) FindTasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTasks", reflect.TypeOf((*MockTaskProvider)(nil).FindTasks), arg0, arg1)
}

// GetTasksByUserID mocks base method.
func (m *MockTaskProvider) GetTasksByUserID(arg0 context.Context, arg1 api.GetTasksByUserIDRequestV1) ([]entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByUserID", arg0, arg1)
	ret0, _ := ret[0].([]entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByUserID indicates an expected call of GetTasksByUserID.
func (mr *MockTaskProviderMockRecorder) GetTasksByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByUserID", reflect.TypeOf((*MockTaskProvider)(nil).GetTasksByUserID), arg0, arg1)
}
