// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dmitriy Basenko",
            "url": "https://github.com/dsbasko/",
            "email": "d.basenko.it@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics": {
            "post": {
                "description": "Выводит аналитику по звонкам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Аналитика звонков",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadAnalytics"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.Analytic"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/analytics/missing": {
            "post": {
                "description": "Выводит аналитику по пропущенным звонкам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Аналитика пропущенных",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadMissedCalls"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/command.AnalyticItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/analytics/missing/check": {
            "patch": {
                "description": "Метит пропущенный звонок как просмотренный",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Пометить пропущенный звонок",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadMissedCallsCheck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.MissedCallCheck"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/analytics/recording": {
            "post": {
                "description": "Выводит список звонков за период с ссылкой на файлы записи",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Получить записи звонков",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadRecordings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/command.AnalyticItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/call/hangup": {
            "patch": {
                "description": "Кладет трубку участника. Работает как в звонке 1 на 1 так и в конференции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "call"
                ],
                "summary": "Положить трубку",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadCallHangup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.Base"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/call/mic": {
            "patch": {
                "description": "Включает или выключает микрофон участника",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "call"
                ],
                "summary": "Включить\\Выключить микрофон",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadCallMic"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.CallMic"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/call/morph-p2p-to-conference": {
            "put": {
                "description": "Переводит из звонка 1 на 1 в конференцию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "call"
                ],
                "summary": "Перевод из в конференцию",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadMorphP2PToConference"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.CallConference"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/conference/add": {
            "patch": {
                "description": "Добавляет участника в конференцию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conference"
                ],
                "summary": "Добавить участника",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadConferenceAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.CallConference"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/conference/create": {
            "post": {
                "description": "Создает конференцию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conference"
                ],
                "summary": "Создать конференцию",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadConferenceCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/command.CallConference"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/p2p/create": {
            "post": {
                "description": "Создает звонок 1 на 1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Создать звонок",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadP2PCrate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/command.CallP2P"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/p2p/redirect": {
            "patch": {
                "description": "Переадресовывает звонок 1 на 1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "p2p"
                ],
                "summary": "Переадресация",
                "parameters": [
                    {
                        "description": " ",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restgin.payloadP2PRedirect"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/command.CallRedirect"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/command.Error"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Функция для проверки связи с микросервисом",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search/{phone}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Кладет трубку участника. Работает как в звонке 1 на 1 так и в конференции",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Положить трубку",
                "operationId": "searchPhone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Номер телефона для поиска",
                        "name": "phone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "137",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "command.Analytic": {
            "type": "object",
            "properties": {
                "answered": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/command.AnalyticItem"
                    }
                },
                "count_answered": {
                    "type": "integer"
                },
                "count_missed": {
                    "type": "integer"
                },
                "duration": {
                    "type": "number"
                },
                "missed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/command.AnalyticItem"
                    }
                }
            }
        },
        "command.AnalyticItem": {
            "type": "object",
            "properties": {
                "call_id": {
                    "type": "string"
                },
                "call_mark": {
                    "type": "string"
                },
                "call_type": {
                    "type": "string"
                },
                "caller": {
                    "type": "string"
                },
                "did": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "file": {
                    "type": "string"
                },
                "is_answered": {
                    "type": "boolean"
                },
                "is_checked": {
                    "type": "boolean"
                },
                "queue": {
                    "type": "string"
                },
                "receiver": {
                    "type": "string"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/command.AnalyticStage"
                    }
                },
                "timestamp": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "command.AnalyticStage": {
            "type": "object",
            "properties": {
                "call_id": {
                    "type": "string"
                },
                "call_mark": {
                    "type": "string"
                },
                "call_type": {
                    "type": "string"
                },
                "caller": {
                    "type": "string"
                },
                "did": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "file": {
                    "type": "string"
                },
                "is_answered": {
                    "type": "boolean"
                },
                "is_checked": {
                    "type": "boolean"
                },
                "queue": {
                    "type": "string"
                },
                "receiver": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "command.Base": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "command.CallConference": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "conference_uuid": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "caller": {
                                "type": "string"
                            },
                            "role": {
                                "type": "string"
                            },
                            "uuid": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "command.CallMic": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "mute": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "command.CallP2P": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "caller": {
                                "type": "string"
                            },
                            "mute": {
                                "type": "boolean"
                            },
                            "role": {
                                "type": "string"
                            },
                            "uuid": {
                                "type": "string"
                            }
                        }
                    }
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "command.CallRedirect": {
            "type": "object",
            "properties": {
                "caller_uuid": {
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "receiver_uuid": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "command.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "command.MissedCallCheck": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "is_checked": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "restgin.payloadAnalytics": {
            "type": "object",
            "required": [
                "date_end",
                "date_start",
                "phones"
            ],
            "properties": {
                "date_end": {
                    "type": "string",
                    "example": "2023-11-07T00:00:00Z"
                },
                "date_start": {
                    "type": "string",
                    "example": "2023-11-06T00:00:00Z"
                },
                "input": {
                    "type": "boolean",
                    "example": true
                },
                "output": {
                    "type": "boolean",
                    "example": true
                },
                "phones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "restgin.payloadCallHangup": {
            "type": "object",
            "required": [
                "uuid"
            ],
            "properties": {
                "uuid": {
                    "type": "string",
                    "example": "1698993296.50511"
                }
            }
        },
        "restgin.payloadCallMic": {
            "type": "object",
            "required": [
                "uuid"
            ],
            "properties": {
                "uuid": {
                    "type": "string",
                    "example": "1698993296.50511"
                }
            }
        },
        "restgin.payloadConferenceAdd": {
            "type": "object",
            "required": [
                "users",
                "uuid"
            ],
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uuid": {
                    "type": "string",
                    "example": "1698993296.50511"
                }
            }
        },
        "restgin.payloadConferenceCreate": {
            "type": "object",
            "required": [
                "users"
            ],
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "restgin.payloadMissedCalls": {
            "type": "object",
            "required": [
                "date_end",
                "date_start",
                "phones"
            ],
            "properties": {
                "date_end": {
                    "type": "string",
                    "example": "2023-11-07T00:00:00Z"
                },
                "date_start": {
                    "type": "string",
                    "example": "2023-11-06T00:00:00Z"
                },
                "phones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skip_checked": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "restgin.payloadMissedCallsCheck": {
            "type": "object",
            "required": [
                "uuid"
            ],
            "properties": {
                "uuid": {
                    "type": "string",
                    "example": "1699245805.52199"
                }
            }
        },
        "restgin.payloadMorphP2PToConference": {
            "type": "object",
            "required": [
                "new_users",
                "uuid"
            ],
            "properties": {
                "new_users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uuid": {
                    "type": "string",
                    "example": "1698993296.50511"
                }
            }
        },
        "restgin.payloadP2PCrate": {
            "type": "object",
            "required": [
                "caller",
                "receiver"
            ],
            "properties": {
                "caller": {
                    "type": "string",
                    "example": "137"
                },
                "receiver": {
                    "type": "string",
                    "example": "138"
                }
            }
        },
        "restgin.payloadP2PRedirect": {
            "type": "object",
            "required": [
                "receiver",
                "uuid"
            ],
            "properties": {
                "receiver": {
                    "type": "string",
                    "example": "139"
                },
                "uuid": {
                    "type": "string",
                    "example": "1698993296.50511"
                }
            }
        },
        "restgin.payloadRecordings": {
            "type": "object",
            "required": [
                "date_end",
                "date_start",
                "phones"
            ],
            "properties": {
                "date_end": {
                    "type": "string",
                    "example": "2023-11-07T00:00:00Z"
                },
                "date_start": {
                    "type": "string",
                    "example": "2023-11-06T00:00:00Z"
                },
                "phones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api/voip",
	Schemes:          []string{},
	Title:            "Voip",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
