// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dsbasko/back-office.uz/apps/todo/internal/services/task (interfaces: Mutator)

// Package mock_service_task is a generated GoMock package.
package mock_service_task

import (
	context "context"
	reflect "reflect"

	entities "github.com/dsbasko/back-office.uz/apps/todo/internal/entities"
	api "github.com/dsbasko/back-office.uz/apps/todo/pkg/api"
	gomock "github.com/golang/mock/gomock"
)

// MockMutator is a mock of Mutator interface.
type MockMutator struct {
	ctrl     *gomock.Controller
	recorder *MockMutatorMockRecorder
}

// MockMutatorMockRecorder is the mock recorder for MockMutator.
type MockMutatorMockRecorder struct {
	mock *MockMutator
}

// NewMockMutator creates a new mock instance.
func NewMockMutator(ctrl *gomock.Controller) *MockMutator {
	mock := &MockMutator{ctrl: ctrl}
	mock.recorder = &MockMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutator) EXPECT() *MockMutatorMockRecorder {
	return m.recorder
}

// CheckTask mocks base method.
func (m *MockMutator) CheckTask(arg0 context.Context, arg1 string, arg2 api.CheckTaskRequestV1) (entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTask indicates an expected call of CheckTask.
func (mr *MockMutatorMockRecorder) CheckTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTask", reflect.TypeOf((*MockMutator)(nil).CheckTask), arg0, arg1, arg2)
}

// CreateTask mocks base method.
func (m *MockMutator) CreateTask(arg0 context.Context, arg1 api.CreateTaskRequestV1) (entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockMutatorMockRecorder) CreateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockMutator)(nil).CreateTask), arg0, arg1)
}
