// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dsbasko/back-office.uz/apps/todo/internal/services/task (interfaces: Provider)

// Package mock_service_task is a generated GoMock package.
package mock_service_task

import (
	context "context"
	reflect "reflect"

	entities "github.com/dsbasko/back-office.uz/apps/todo/internal/entities"
	api "github.com/dsbasko/back-office.uz/apps/todo/pkg/api"
	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// FindTask mocks base method.
func (m *MockProvider) FindTask(arg0 context.Context, arg1 api.FindTaskRequestV1) (entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTask", arg0, arg1)
	ret0, _ := ret[0].(entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTask indicates an expected call of FindTask.
func (mr *MockProviderMockRecorder) FindTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTask", reflect.TypeOf((*MockProvider)(nil).FindTask), arg0, arg1)
}

// FindTasks mocks base method.
func (m *MockProvider) FindTasks(arg0 context.Context, arg1 api.FindTasksRequestV1) ([]entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTasks", arg0, arg1)
	ret0, _ := ret[0].([]entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTasks indicates an expected call of FindTasks.
func (mr *MockProviderMockRecorder) FindTasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTasks", reflect.TypeOf((*MockProvider)(nil).FindTasks), arg0, arg1)
}

// GetTasksByUserID mocks base method.
func (m *MockProvider) GetTasksByUserID(arg0 context.Context, arg1 api.GetTasksByUserIDRequestV1) ([]entities.RepositoryTaskEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByUserID", arg0, arg1)
	ret0, _ := ret[0].([]entities.RepositoryTaskEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByUserID indicates an expected call of GetTasksByUserID.
func (mr *MockProviderMockRecorder) GetTasksByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByUserID", reflect.TypeOf((*MockProvider)(nil).GetTasksByUserID), arg0, arg1)
}
