server {
	listen 80;
	listen [::]:80;
	server_name localhost;

	location / {
		proxy_pass http://frontend:3000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	}

	location /api {
		proxy_pass http://api:3000;
		rewrite ^/api/(.*)$ /$1 break;
	}

	location /api/voip {
		proxy_pass http://voip:3000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
		rewrite ^/api/voip/(.*)$ /$1 break;
	}

	location /api/account_1c {
		proxy_pass http://account_1c:3000;
		rewrite ^/api/account_1c/(.*)$ /$1 break;
	}
}
